[tool.poetry]
name = "akvq"
version = "0.0.2"
description = "Get secrets from azure key vaults quick and easy"
authors = ["Viktor Freiman <freiman.viktor@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
akvq = "src.akvq:main"

[tool.poetry.dependencies]
python = "^3.6.2"
azure-identity = "^1.10.0"
azure-keyvault-secrets = "^4.4.0"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
flake8 = "^4.0.1"
flake8-bugbear = "^21.9.2"
flake8-quotes = "^3.3.1"
rinohtype = "^0.5.3"
Sphinx = "^4.2.0"
sphinx-argparse = "^0.3.1"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^1.0.0"
sphinxcontrib-kroki = "^1.3.0"
toml = "^0.10.2"
sphinx-copybutton = "^0.5.0"
docs-helper = "^0.0.9"
pytest = "~7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
